// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlMIadQsuHoJkAV7DNP0kobmmMXIGP6H0',
    appId: '1:723620515755:web:af1fc6102b42bd4a71ccee',
    messagingSenderId: '723620515755',
    projectId: 'plantifyapp-b5a8b',
    authDomain: 'plantifyapp-b5a8b.firebaseapp.com',
    storageBucket: 'plantifyapp-b5a8b.firebasestorage.app',
    measurementId: 'G-45VD878GYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-E_FggiXN4-FJ3tltdZJ_iiDyxMH2Eso',
    appId: '1:723620515755:android:3cd0801a394d2ab871ccee',
    messagingSenderId: '723620515755',
    projectId: 'plantifyapp-b5a8b',
    storageBucket: 'plantifyapp-b5a8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZLCtbYZGAKS3bPaQeDl-ifvPgGa4MBHw',
    appId: '1:723620515755:ios:e7a027c39f18feb971ccee',
    messagingSenderId: '723620515755',
    projectId: 'plantifyapp-b5a8b',
    storageBucket: 'plantifyapp-b5a8b.firebasestorage.app',
    iosBundleId: 'com.example.plantify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZLCtbYZGAKS3bPaQeDl-ifvPgGa4MBHw',
    appId: '1:723620515755:ios:e7a027c39f18feb971ccee',
    messagingSenderId: '723620515755',
    projectId: 'plantifyapp-b5a8b',
    storageBucket: 'plantifyapp-b5a8b.firebasestorage.app',
    iosBundleId: 'com.example.plantify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlMIadQsuHoJkAV7DNP0kobmmMXIGP6H0',
    appId: '1:723620515755:web:9c0f83aec09a75c071ccee',
    messagingSenderId: '723620515755',
    projectId: 'plantifyapp-b5a8b',
    authDomain: 'plantifyapp-b5a8b.firebaseapp.com',
    storageBucket: 'plantifyapp-b5a8b.firebasestorage.app',
    measurementId: 'G-E7RFN24ZMQ',
  );
}
